local AddonName, Addon = ...

Addon.localization = {
    CLEANDBBT  = "Clean database",
    CLEANDBTT  = "Clear the addon internal base with the percent of monsters.\nHelps if the percent counter is buggy",
    CLOSE      = "Close",
    CUSTOMIZE  = "Customize frame",
    CCAPTION   = "Main frame: LMB - move, RMB - resize\nElement: LMB - move, RMB - font size",
    DAMAGE     = "Damage",
    DEATHCOUNT = "Deaths",
    DEATHSHOW  = "Click for detail information",
    DEATHTIME  = "Time lost",
    DTHCAPTION = "Deaths history",
    FONT       = "Font",
    FONTSIZE   = "Font size",
    MAPBUT     = "LMB (click) - toggle options\nLMB (drag) - move button",
    MAPBUTOPT  = "Show/Hide minimap button",
    MELEEATACK = "Melee attack",
    OPTIONS    = "Options",
    OPACITY    = "Background opacity",
    RESTORE    = "Restore",
    SCALE      = "Scale",
    SOURCE     = "Source",
    STARTINFO  = "iP Mythic Timer loaded. Type /ipmt for options.",
    TIME       = "Time",
    WHODIED    = "Who died",
}
